### ISSUE TITLE
A07 Admin: Treasury Management

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#14]
Related to https://github.com/bitcoin-sv/bsv-faucet/issues/17 and https://github.com/bitcoin-sv/bsv-faucet/issues/13

Description:
For admins (role = 2) there will be a dedicated section /admin to allow them to see and manage the overall treasury.

Allow an admin to be able to view their amount, and hit a "Mine Block" function if their reserves run below 10 BSV.

This should initiate a fresh batch of BSV to the master treasury wallet.

- Show the total treasury reserves in the master wallet.
- Display in BSV and Satoshis
- Only allow the Mine Blocks function Display an alert if the balance is running low (below 10 BSV)

**Acceptance Criteria:**
0. Ensure the database schema structure is created and migration scripts run.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I have a strong background in full-stack development, particularly in building administrative dashboards for managing resources and user interactions. My experience with blockchain technology and wallet management enables me to implement secure and efficient solutions for treasury management. Additionally, I have worked with real-time data updates and alerts, which will be crucial for ensuring that admins can monitor treasury reserves effectively and respond promptly to low balance situations.

### How I plan on tackling this issue
To implement the admin treasury management functionality, I will create a dedicated /admin section for users with the admin role (role = 2). This section will display the total treasury reserves from the master wallet, including amounts in both BSV and Satoshis.

Displaying Treasury Reserves: I will fetch the current balance of the treasury wallet and present it clearly, ensuring that both the BSV and Satoshis values are visible for ease of understanding.

Low Balance Alert: I will implement a warning system that alerts admins when the treasury balance falls below 10 BSV. This alert could take the form of a visual notification (e.g., a red banner) on the dashboard to draw attention to the issue.

"Mine Block" Functionality: When the treasury balance is low, I will enable a "Mine Block" button that allows admins to initiate a fresh batch of BSV to the master treasury wallet. This function will be implemented with appropriate checks to ensure that it can only be accessed when the balance is below the threshold.

Testing and Validation: I will include tests to verify that the treasury reserves are displayed accurately, that alerts trigger correctly, and that the "Mine Block" function operates as intended without any unauthorized access.

User Experience: I will ensure that the interface is intuitive, providing clear instructions and feedback to the admins on their actions regarding the treasury management.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
i have attend tsoc recently and i have experience in this project

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by deeseeker** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a React developer with over two years of experience and have recently developed a strong interest in blockchain technology. I have valuable experience navigating codebases and I have recently implemented a similar task for Starknet React by implementing add token hook and writing a test for the hook.

As someone still learning, I am happy to take on the challenge to work on this task.

### How I plan on tackling this issue
Clone the project on my pc
Spin it up following the documentation
Review the existing codebase 
Implement function
Test the function to ensure all use cases are passed
Document the function

**Comment by ikemHood** [comment]
Hey @mo-jaber most of the requirement for this issue was met by #36 except the mine blcok button|function that should trigger some mining activities.

can you please re-assign me so I create a PR that implement this
Also, If i can get some clearity on how we trigger the mining activities

**Comment by Benjtalkshow** [comment]
Hello @mo-jaber 
Please i really wanna work on this. I will deliver a quality work.

**Comment by 0xdevcollins** [comment]
I can work this sir @mo-jaber .

**Comment by mimisavage** [comment]
I’d like to resolve this. I will make a PR as soon as possible
