### ISSUE TITLE
A00: Create Treasury Wallet

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#17]
**Description:**
Establish a base wallet that connects to the regtest node, which is actively mining blocks on the testnet network. This will be the treasury where funds are held and distributed to users on request. 

Configure this base wallet to serve as the treasury wallet for holding testnet BSV tokens.

**Transaction Storage & Tracking**
Store all wallet transactions in the database with the following details:
1. Date of Transaction: Record the date and time of each transaction.
2. TXID: Store the transaction ID for unique identification.
3. Raw Transaction (Raw TX): Save the raw transaction data.
4. Beef Transaction (Beef TX): Include parsed transaction details for further analysis.
5. Vout (Output Tracking) - Track outputs to determine whether they are spendable or not.
7. Transaction Type (TX Type): Define the type of transaction (e.g., incoming, outgoing).
8. Spent Status:  - Initially set to false when a transaction is received. Mark the transaction as Spent (true) or Unspent (false). Update to true when the transaction has been used or sent to a user.
9. Testnet Flag: - Set a flag indicating the transaction is on the testnet (true).
10. Amount (in Satoshis): Record the transaction amount in satoshis for precision.

This information will be displayed and managed in the front end;

See: 
https://github.com/bitcoin-sv/bsv-faucet/issues/13
https://github.com/bitcoin-sv/bsv-faucet/issues/14
https://github.com/bitcoin-sv/bsv-faucet/issues/15

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
i have attend tsoc recently and i have experience in this project

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by binayak9932** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
Iam new to OS and i am a python dev  with learning web3 technologies. I am highly motivated and eager to contribute meaningfully to solve the issue. I'm confident that my Python expertise,and current knowledge of web3 stack i can solve this task.

### How I plan on tackling this issue
I would implement basic wallet functionality for storing funds and distributing tokens. It includes Paymail integration, allowing users to send tokens to Paymail addresses, simplifying the process of fund transfers. The wallet will also supports multi-recipient token distribution, providing an efficient way to distribute tokens to multiple addresses in a single transaction.

**Comment by binayak9932** [comment]
Gm chief. Sorry for the inconvenience, there was a cyclone here so was a little disoriented with no electricity 
I have created the wallet, I will push the changes and the implementation in few hours
Thank you for your patience

**Comment by 0xdevcollins** [comment]
May I pick this up?

**Comment by mo-jaber** [comment]
Assgined @0xdevcollins
