### ISSUE TITLE
A04 Admin: User Management

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#3]
dependency on https://github.com/bitcoin-sv/bsv-faucet/issues/11

**Description:**

Allow an admin to see/manage all users across the platform.

Set up role type = 2 account for an Admin, to provide a different view/permissions/functions beyond a regular user account (role =1)

--
**View:**
Admin can see all the regular pages that a regular user can see, but will have additional view /users

**Functional requirements for the following page:**
**/users** 

Show the entire user list, in a table, sorted by oldest to newest of registration date. 
- Allow export to .csv
- Allow Sort By and Filter by
- Allow smart search
- Clicking the row should take you directly to blockexplorer [[test.whatsonchain.com](http://test.whatsonchain.com/)](http://test.whatsonchain.com/) for that txid

Tabled format:

- userid
- email
- type
- date registered
- total withdrawn (BSV)
- Actions (pause account or delete account)

**Acceptance Criteria:**
0. Ensure the database schema structure is created and migration scripts run.

**Comment by Jemiiah** [comment]
@mo-jaber would love to contribute to this issue when OD Hack start

**Comment by 0xdevcollins** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
My name is Collins Ikechukwu. I'm a full stack blockchain developer developer.


### How I plan on tackling this issue
To implement this feature, I would first set up role-based access control, ensuring that admins (role = 2) have access to additional features beyond what regular users (role = 1) can see. I’ll grant the admin access to the `/users` page, where they can manage all platform users.

On the `/users` page, I’ll display the entire user list in a table, sorted from oldest to newest by registration date. I’ll also add the ability to export the user list to `.csv` and provide options to sort and filter the data based on different criteria (e.g., date registered, user type). A smart search feature will enable quick access to specific users.

Each row will display the following details: `userid`, `email`, `type`, `date registered`, `total withdrawn (BSV)`, and action buttons to either pause or delete the account. Clicking a user’s row will redirect the admin to blockexplorer at [test.whatsonchain.com](http://test.whatsonchain.com/) using the `txid` of that user’s transactions, making it easy to track related blockchain data.

**Comment by Jayse007** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I have intensive knowledge using python to write codes and program. I have worked with the csv module that it provides. I also work with the django framework for backend development. With the aid of these two tools, I believe this is an easy task to accomplish.

### How I plan on tackling this issue
I would extract the data in the specified order format according to the oldest to newest registration from the database. After that, I would use a loop to save all the data in an opened file, and save the specified data in a csv file making use of csv module to create headers, and fill the data in row by row with each iteration.

**Comment by saimeunt** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I'm the maintainer of op-scan (https://github.com/walnuthq/op-scan) a blockchain explorer with a very similar tech stack so I'm familiar with the patterns and best practices used in this project. I will use my XP in Full Stack Web3 Development to implement this issue.

### How I plan on tackling this issue
The user story being self explanatory, I will carefully implement it using the latest Next.js best practices, choosing the right shadcn/ui component for the job. I will probably use a Data Table to let the admin filter/sort the entire user table. I will use an API route to get the data in CSV.

**Comment by Benjtalkshow** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a Full Stack Developer specializing in Next.js, TypeScript, Node.js, Cairo and Rust . With over 31 contributions across projects in the OnlyDust ecosystem, I’ve developed strong proficiency in delivering high-quality solutions and resolving complex issues within tight deadlines. My experience spans frontend, backend, smart contracts, and the optimization and maintenance of scalable codebases.

### How I plan on tackling this issue
I will develop a comprehensive /users page that allows admins to manage all users across the platform. This page will be accessible only to accounts with a role type of 2, distinguishing them from regular users (role = 1). Admins will have a different view, providing them with the necessary permissions and functions to effectively manage user accounts.

On the /users page, I will display a complete list of users in a table format, sorted by their registration date from oldest to newest. The table will include columns for user ID, email, account type, registration date, total withdrawn (in BSV), and actions. Admins will be able to export the user list to a .csv file for easy analysis and reporting.

I will also implement sorting and filtering options to help admins quickly find specific users. A smart search feature will allow for efficient user lookup. Additionally, clicking on a user’s row will redirect admins to the block explorer at test.whatsonchain.com for that user’s transaction ID. The actions column will provide options to pause or delete user accounts as needed, enabling admins to manage user accounts effectively and maintain platform integrity.

**Comment by NueloSE** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
i am a software developer with experience in frontend technologies and smart contract integration. 

### How I plan on tackling this issue
below is just my thought process on how to implement it a general psueduo code on how i will implement the above task

Admin Role Setup:

I will create an admin role (role_type = 2) with elevated permissions, distinguishing it from regular users (role_type = 1). I’ll ensure that, as an admin, I can view all the pages accessible to regular users, with an additional page, /users, for managing platform users.

Admin User Management View:

I will design a dedicated /users page where I can manage all users. The page will display a table with columns for user ID, email, account type, registration date, total BSV withdrawn, and action buttons to pause or delete an account.

Table Features:

Sorting: I will automatically sort the table from the oldest to newest registration date.
Filtering and Sorting: I’ll implement filter and sort options on various columns, such as registration date and user type.
Smart Search: I will add a search bar to help me quickly locate users by relevant information, such as email or user ID.
CSV Export:

I’ll enable the export of the user list into a .csv file for external use or reporting.

Transaction Link:

When I click on any user row, I will be directed to a transaction explorer (e.g., WhatsOnChain) for the specific txid associated with that user’s transactions.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I have a solid background in full-stack web development, with experience in building user management systems and implementing role-based access controls. My expertise includes working with front-end frameworks (such as React or Angular) and back-end technologies (like Node.js or Django), which equips me to create a comprehensive admin dashboard that meets the specified functional requirements. Additionally, my familiarity with data export functionality and database management will enable me to efficiently implement user sorting, filtering, and searching features.

### How I plan on tackling this issue
To address the issue of allowing an admin to manage all users across the platform, I would first establish a clear understanding of the functional requirements specified for the `/users` page. I would implement role-based access control to differentiate between regular users and admins, ensuring that the admin view includes the additional functionalities required. 

Next, I would create a user management interface that displays a comprehensive list of users in a sortable and filterable table format, complete with pagination for ease of navigation. I would integrate a smart search feature to allow quick access to specific users based on user ID or email. 

For exporting user data to .csv, I would utilize a library to handle the file generation seamlessly. Additionally, I would ensure that clicking on a user's row directs the admin to the corresponding block explorer for further transaction details. To enhance usability, I would implement action buttons for account management, such as pausing or deleting accounts, accompanied by necessary confirmation dialogs to prevent accidental actions. 

By following this approach, I would ensure a user-friendly and efficient admin management system that meets the specified requirements.

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by jimenezz22** [comment]
I am Luis Jiménez, an active member of the Dojo Coding community in Costa Rica, with experience in Cairo and TypeScript. 

Here’s my approach to solving this issue:

1. **Admin Role (role = 2):**
   - I will create a separate role (role = 2) for admins and ensure they have access to both the regular user views and an additional `/users` view, while still retaining permissions specific to admins.

2. **User List View:**
   - On the `/users` page, I will display a table that shows all users, sorted by registration date (oldest to newest by default).
   - Columns will include `userid`, `email`, `type`, `date registered`, `total withdrawn (BSV)`, and `actions`.

3. **Table Functionalities:**
   - **Sort By and Filter By**: I’ll implement features that allow sorting and filtering based on columns (e.g., sort by date, filter by user type).
   - **Smart Search**: A search bar will be included for smart searching by email, userid, or any other relevant column.
   - **Export to CSV**: I’ll implement a button to export the user list as a `.csv` file.
   - **Clickable Rows**: Clicking on a user row will take the admin directly to the block explorer at [test.whatsonchain.com](http://test.whatsonchain.com/) for the relevant transaction ID (`txid`).

4. **Actions (Pause/Delete Account):**
   - Each user will have action buttons to pause or delete their account. I’ll implement confirmation dialogs for these actions to prevent accidental deletions or pauses.

5. **Testing and Polishing:**
- Test all functionalities, including sorting, filtering, smart search, and the export feature.
- Validate that the pause and delete actions work correctly and that clicking rows properly redirects to the block explorer.

**Comment by mo-jaber** [comment]
@saimeunt Will you be submitting a PR in the next few hours?

**Comment by Jemiiah** [comment]
I can work on it within a few hours and create a draft PR

**Comment by ShantelPeters** [comment]
> I can work on it within a few hours and create a draft PR

Hey, this is wrong, I'll assume that you can clearly see that it was assigned to me already.

**Comment by mo-jaber** [comment]
Yes this has been reassigned to @ShantelPeters

**Comment by mo-jaber** [comment]
Hi @ShantelPeters we have successfully deployed a new baseline with Clerk integration fully working. 

re dependency ticket https://github.com/bitcoin-sv/bsv-faucet/issues/11 

.env.example file is updated 

you can use these values: 

NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=
NEXT_PUBLIC_CLERK_SIGN_IN_URL=/sign-in
NEXT_PUBLIC_CLERK_SIGN_UP_URL=/sign-up

Let me know if you have any further questions

**Comment by ShantelPeters** [comment]
@mo-jaber Oh nice, on it.

**Comment by mo-jaber** [comment]
Hows it going @ShantelPeters

**Comment by ShantelPeters** [comment]
> Hows it going @ShantelPeters

Fine sir .. I’m making progress 
If I need help I will definitely reach out to you

**Comment by mo-jaber** [comment]
@ShantelPeters how are you going?

**Comment by mo-jaber** [comment]
@saimeunt I have re-assigned this to you since you are familiar with user management flow

**Comment by mo-jaber** [comment]
Hi @saimeunt - we have 3 hours left before closing. How are you going?
