### ISSUE TITLE
A11: Migrate the project to the Prisma ORM

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#33]
Ensure all existing issues and future issues that have an postgres db schema are all migrated to Prisma OSM. 

Ensure the readme file is updated as per latest instructions required

**Comment by Jemiiah** [comment]
@mo-jaber pls can I work on this issue

**Comment by PoulavBhowmick03** [comment]
Gm, I can work on this issue
I have previously contributed and merged my PR in this repository. I have a good knowledge of working with Prisma ORM and Next.js projects. I will take a look at the current db schema, migrations and the integrations and migrate all the changes to Prisma

ETA - 2 to 3 days

**Comment by mo-jaber** [comment]
Great - thank you @PoulavBhowmick03

**Comment by mo-jaber** [comment]
@PoulavBhowmick03 as part of this issue, ensure we are only using Prisma ORM (and remove the references to Drizzle etc)

**Comment by PoulavBhowmick03** [comment]
> @PoulavBhowmick03 as part of this issue, ensure we are only using Prisma ORM (and remove the references to Drizzle etc)

Yes chief! Leave that on me. The entire project will only have prisma integrated and will remove knex js and drizzle entirely
