### ISSUE TITLE
A09 User: Donate tokens back to Faucet

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#4]
**Description:**
BSV Testnet tokens are limited supply, provide a mechanism to allow deposits to return unused coins.

**User story:**
As a user, I want to donate my unused or extra testnet coins back to the master treasury account, so that I can contribute to the faucet’s sustainability and reduce excess coins in circulation

**Acceptance criteria:**
- I can access the "Donate to Faucet" option in the faucet interface inside the /dashboard section. 
- The system displays a predefined, verified master wallet address to which users can send their testnet coins.
- I can select the amount of testnet coins I want to donate from my available balance.
- After confirming the donation, the system generates a transaction that sends the selected amount to the master treasury faucet address.
- A success message, along with the transaction ID, is shown after the coins are donated (in my /requests history page)
- I can track the donation transaction on the testnet explorer via a txid testnet blockchain explorer link.

**Comment by mo-jaber** [comment]
**Description:**

BSV Testnet tokens are limited supply, provide a mechanism to allow deposits to return unused coins. 

**User story:**
As a user, I want to donate my unused or extra testnet coins to a burn address, so that I can contribute to the faucet’s sustainability and reduce excess coins in circulation

**Acceptance criteria:**
1. I can access the "Donate to Faucet" option in the faucet interface inside the /wallet.
2. The system displays a predefined, verified burn address to which users can send their testnet coins.
3. I can select the amount of testnet coins I want to donate from my available balance.
4. After confirming the donation, the system generates a transaction that sends the selected amount to the master treasury faucet address.
5. A success message, along with the transaction ID, is shown after the coins are donated.
6. I can track the donation transaction on the testnet explorer via a provided link.

**Comment by KodeSage** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I'm James Harrison, A Season Software Engineer and an active contributor here in Onlydust. well versed in Typescript, Javascript, Solidity and Rust.

### How I plan on tackling this issue
## Add "Donate to Faucet" Option:
- In the /dashboard section, create a new interface element like a button or card for the "Donate to Faucet" feature.
- Ensure it's easily accessible, with clear labeling and guidance text about why donating unused coins is important.

## Input for Coin Selection:
- Add a field or slider that allows the user to choose how many testnet coins they want to donate from their available balance. This can be restricted to amounts that the user currently holds.

## Predefined Master Wallet Address:
- Display the master faucet address prominently on the donate page, with text stating that it’s verified and safe to use.

## Transaction Confirmation Modal:
- When the user selects the amount to donate, show a modal to confirm their action before processing the donation. It should contain: The amount of coins,
The master faucet address,
A “Confirm” button and a “Cancel” button.

## Fetching User's Balance:
- Use the user's testnet wallet address to retrieve their current balance in real-time and display it on the donation screen.

## Transaction Generation
- After the user confirms the donation, generate a transaction that sends the selected amount of testnet coins to the master faucet address.
- Interact with the BSV Testnet blockchain to create and sign this transaction.
- Use appropriate BSV libraries or APIs to broadcast the transaction to the testnet network.

**Comment by ikemHood** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
Hello, I would love to handle this,

### How I plan on tackling this issue
Implementation steps:

- Add DonationForm component to dashboard
- Create donation API endpoint
- Implement wallet service function
- Update request history component
- Update database schema
- Add tests

To test:

- Test donation with various amounts
- Verify transaction creation
- Check history updates
- Verify explorer links
- Test error handling
- Check balance updates

**Comment by blessingbytes** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
Hello, i'm a frontend and blockchain developer, i will love to work on this issue

### How I plan on tackling this issue
- I will include a "Donate to Faucet" option in the faucet interface within the /dashboard section, allowing users to easily access the donation feature.
- i will Display Master Wallet Address
- I will implement a selection mechanism for users to choose the amount of testnet coins they wish to donate from their available balance.
- I will generate a transaction that sends the selected amount to the master treasury faucet address.
- After the donation transaction is completed, I will show a success message along with the transaction ID.

**Comment by ShantelPeters** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
For the "Donate to Faucet" feature, I bring a strong background in full-stack web development, particularly in building user interfaces and handling backend transactions. My experience includes implementing role-based access controls and ensuring secure, efficient transactions in decentralized applications. I understand the importance of user experience and clarity in financial interactions, which will help me create a seamless donation process. I will leverage this knowledge to ensure that users can easily donate their testnet coins, view transaction confirmations, and track their donations effectively.

### How I plan on tackling this issue
**Approach to the Problem:**

To implement the donation mechanism for unused testnet coins, I will begin by designing the user interface within the `/dashboard` section, ensuring that the "Donate to Faucet" option is easily accessible. I will display a verified master wallet address, allowing users to see where their donations will be sent. 

Next, I will integrate a feature that enables users to select the amount of testnet coins they wish to donate from their available balance. After the user confirms the donation, I will create a transaction that transfers the specified amount to the master treasury faucet address. 

To enhance user experience, I will implement a success message upon donation completion, along with the transaction ID that links to their donation in the `/requests history` page. Additionally, I will provide a link to the testnet explorer for tracking the transaction using the transaction ID. 

Throughout the development process, I will ensure that the functionality aligns with the acceptance criteria, focusing on usability, security, and error handling to create a seamless donation experience for users.

**Comment by emarc99** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I have a strong background in blockchain development, with expertise in writing Solidity, and fundamental knowledge of Cairo, and zero-knowledge proofs (zk). I have built dApps on Ethereum (and Scroll) using token standards; UniSwapv2 clone, Multi wallet, Gated NFT Event Management system, Crowdfunding. I also do FE/wallet integration using Reown, web3js and ethersjs. As well as subgraph for efficient indexing.

This experience enables me to design and implement a secure and efficient donation mechanism for the BSV Testnet, ensuring that users can easily contribute their unused coins to the master treasury while maintaining a seamless user experience.

### How I plan on tackling this issue
1.0 Smart Contract Writing & Logic
1.1 Contract Design: Create a smart contract that defines the donation mechanism, the master wallet address as a verified constant address variable during deployment, and donations handling.
1.2 Transaction Logic: The contract would include necessary sanitary checks e.g. the user's balance, ensure the donation amount is valid, and implement transfer of  approved tokens from the user to the master treasury/wallet address.
1.3 Event Emission: Implement events to log successful donations on testnet explorer.

2.0 Frontend Writing (React & Hooks)
2.1 User Interface Design: Create relevant layout (pages). Include a "Donate to Faucet" button and a form in /dashboard section for users to input donate amount. After a successful donation, show success message with React Toast and save the transaction details in the /requests history section.
2.2 State Management: Utilizing React hooks, handle user's balance, user inputs, master wallet address' balance. 
2.3 Error Handling: Provide feedback to users in case of insufficient balance or transaction failures with React Toast.

3.0 Integration
3.1 Blockchain Interaction: Integrate the frontend with the smart contract using a Reown/Wagmi (RainbowKit), allowing users to interact with the blockchain directly from the UI.
3.2 Transaction Confirmation: After a user signs (confirms) their donation, the system should generate a transaction and send the selected amount to the master treasury.
3.3 Explorer Link: After the transaction is completed, generate a link to the testnet blockchain explorer from the UI so the user can track the donation.
3.4 History and Transaction Tracking: Save the transaction hash and details in the user's request history to make the donation traceable.

**Comment by suhas-sensei** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
i have participated in tsoc and have prior experience with regard

**Comment by aniruddhaaps** [comment]
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/bsv-blockchain-faucet).

### My background and how it can be leveraged
I am a python dev . A new-comer here, willing and ready to contribute to solve the  issue.

**Comment by ikemHood** [comment]
🚀

**Comment by mo-jaber** [comment]
Thank you @ikemHood successfully merge.
