### ISSUE TITLE
A12 - DB, Clerk, Blockchain functional gaps

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#52]
1. Link Clerk and DB for all activity in platform
- Ensure clerk and db talk to eachother.
- This primarykey (userid/email) will become the reference for where the user activity, requests history (txid etc), settings will be associated with on the platform

2. blockchain transaction activity captured for master wallet and each user request.
- we are not building a user wallet (only a mechanism for them to be able to enter their wallet address —-> send to their wallet outside the platform), however as we should always be capturing the utxos and txos from the master wallet (and their spend status flag) then all of this can be tied 

3. Ensure permissioned view for roles are as expected, as per the setting of user or admin. 

User can only see
- dashboard
- request history
- settings

Admin can see all of the above and:
- admin

**Comment by ikemHood** [comment]
Can I get this done @mo-jaber

**Comment by Jemiiah** [comment]
can i work on this issue @mo-jaber

**Comment by 0xdevcollins** [comment]
@mo-jaber can I be assigned this issue

**Comment by mo-jaber** [comment]
Thanks @0xdevcollins great work
