### ISSUE TITLE
A13 - Remaining platform gaps/enhancements

### ISSUE THREAD

**Issue by mo-jaber** [bitcoin-sv/bsv-faucet#55]
/admin
[x] fix admin page
[x] loading state for UX (all pages)

Fix functions on admin page
[ ] Balance in BSV is incorrect
[ ] Balance in Satoshis is incorrect
[ ] Clicking the "Details" button. Sometimes it shows the modal, sometimes it shows the old page of postgres table inserts
[ ] beef TX is incorrect
**[ ] vOut is incorrect

/dashboard
[ ] capture 24hr daily limit of 0.001 / 100,000 satoshis tied to the userid/e-mail (rather than the wallet address) 

/requests
[ ] on /request page, in super admin view, where account = blank because it is a deposit, display 'Admin - Treasury Wallet.'
[ ] under Beef Tx, show the Background Evaluation Extended Format (see https://beef.xn--nda.network/) 
[ ] hide spent status in UI
[ ] Hide all deposits entries. (these will be visible in the /admin page)

db.transaction
[ ] store beefTx
**[ ] store vOut
**[ ] store spent status, linked to the txos and vout

/users
[ ] show the aggregated withdrawn amount for each user (currently showing '0')

/settings
[ ] dark mode toggle

**Comment by ikemHood** [comment]
Can I jump on this @mo-jaber

**Comment by 0xdevcollins** [comment]
Can I work on this @mo-jaber

**Comment by OWK50GA** [comment]
I can jump on it when it is confirmed, @mo-jaber
